### ISSUE TITLE
el.insertAdjacentHTML is not a function

### ISSUE THREAD

**Issue by arnoabraham** [gavruk/angular-card#10]
When trying to load the card. (Using your example code) it keeps giving the el.insertAdjacentHTML is not a function error.

**Comment by arnoabraham** [comment]
Linking the original card library as script fixed it.

**Comment by gavruk** [comment]
Yeah, of course you need original card.js :)

**Comment by refaelos** [comment]
@arnoabraham what do you mean `Linking the original card library` ?
The `el.insertAdjacentHTML` is already from the original card library so you had it linked ...

(I'm just saying b/c I have the exact same problem and can't figure out a way to fix it)

**Comment by gavruk** [comment]
@refaelos as I understood, he forgot to include js from https://github.com/jessepollak/card

```
 <script src="../bower_components/card/lib/js/card.js" type="text/javascript"></script>
```

To be able to work, you need both `card/card.js` and `angular-card/card.js`

**Comment by arnoabraham** [comment]
You need to load the original card.js library first and than the angular-card.js. If you only load angular-card.js it won't work. 

As @gavruk  said :)

**Comment by refaelos** [comment]
@gavruk @arnoabraham This error is coming from card.js so it's linked already.

see the stack:

```
TypeError: el.insertAdjacentHTML is not a function
    at Function.QJ.append (http://localhost:9000/bower_components/card/lib/js/card.js:1646:13)
    at Card.render (http://localhost:9000/bower_components/card/lib/js/card.js:1795:8)
    at new Card (http://localhost:9000/bower_components/card/lib/js/card.js:1788:10)
    at link (http://localhost:9000/bower_components/angular-card/src/card.js:82:9)
    at http://localhost:9000/bower_components/angular/angular.js:8783:44
    at invokeLinkFn (http://localhost:9000/bower_components/angular/angular.js:8789:9)
    at nodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:8289:11)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7680:13)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7684:13)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7684:13)
```

**Comment by gavruk** [comment]
Can you show me what version of angular, card and angular-card you have installed?

**Comment by refaelos** [comment]
Sure.
"angular": "1.4.7"
"angular-card": "~0.3.4"

`card` is actually a dependency in `angular-card` so it fetches it automatically. Looking into your bower.js it looks like you're fetching `card: >=1.1.0`

**Comment by refaelos** [comment]
Looks like it fetched `card#1.2.2`

**Comment by gavruk** [comment]
Will be great if you can provide a simple html/js that reproduces this issue. Because I cannot reproduce

**Comment by refaelos** [comment]
I wish I could :) It's deep inside the angular app. Do you want to remote control my machine and take a look?

**Comment by gavruk** [comment]
Can you just paste the parts where you:
1) include card.js and angular-card.js
2) define a form for card
You can also try to update angular-card to v0.3.5 and re-install bower modules, but I don't think this will help

**Comment by refaelos** [comment]
1) I include card.js and angular-card.js using lazyloading.

```
            {name: 'angular.card',               files: ['bower_components/card/lib/js/card.js',
                                                        'bower_components/angular-card/src/card.js'], serie: true}
```

2) The form is exactly like the example:

```
<form 
          name="cardForm"
          data-card
          data-width="500"
          data-card-container="#card-container"
          data-placeholders="cardPlaceholders"
          data-options="cardOptions"
          data-messages="cardMessages"
          class="form-horizontal">

      <div>
        <input placeholder="Card number" type="text" name="CardNumber" card-number data-ng-model="card.number" />

        <input placeholder="Full name" type="text" name="CardName" card-name data-ng-model="card.name" />
      </div>
      <div>
        <input placeholder="MM / YYYY" type="text" name="CardExpiry" card-expiry data-ng-model="card.expiry" />

        <input placeholder="CVC" type="text" name="CardCvc" card-cvc data-ng-model="card.cvc" />

        <input type="button" value="Change card" data-ng-click="changeCard()" />
        <input type="button" value="Clear" data-ng-click="clear()" />
      </div>

    </form>
```

I'll try to update.

**Comment by gavruk** [comment]
You can also try to clone https://github.com/gavruk/angular-card, run `bower install` and then open `example/example.html` to see if it works for you.
Maybe the issue is with lazy loading

**Comment by refaelos** [comment]
Finally I got it... I didn't set the card-container correctly. I didn't have the div that correlates that variable.

Sorry for the hassle guys. Thanks!

**Comment by gavruk** [comment]
@refaelos great that you solved this. This will help people who will have this issue in future :)

**Comment by ivanstojkovicapps** [comment]
Hi,

getting the same error when using modal panel with ui.bootstrap.modal
Moving it to normal container (not modal) works perfectly.
Is this an known issue?

best regards Ivan

**Comment by brunovinny** [comment]
@ivanstojkovicapps  did you fix that modal's issue? I'm have the same problem here.

**Comment by aviadhahami** [comment]
For the sake of future mistake-makers:
If your container is under `ng-if` (and evaluated falsy) at the time the `form` (or `new Card`) was called, it will yield the above error as the container element isn't present on the DOM.

quick solve - change to `ng-show` 👍
