### ISSUE TITLE
cardNumber directive not found

### ISSUE THREAD

**Issue by kyawmyintthein** [gavruk/angular-card#12]
Error: [$compile:ctreq] Controller 'card', required by directive 'cardNumber', can't be found!

**Comment by gavruk** [comment]
Can you show your html form?

**Comment by kyawmyintthein** [comment]
My Error Message is 
TypeError: $(...).card is not a function

![screen shot 2015-10-21 at 5 40 46 pm](https://cloud.githubusercontent.com/assets/3658706/10633072/e906c6ca-781a-11e5-9c43-ccd1a07d3b95.png)

**Comment by gavruk** [comment]
Have you included original card.js script?
You need to include both card.js and angular-card.js

**Comment by kyawmyintthein** [comment]
Ya! I have!

**Comment by gavruk** [comment]
Seems that you included `card.js`, but you need to include `jquery.card.js`
In latest versions of angular-card you don't need jquery and should use `card.js`

**Comment by kyawmyintthein** [comment]
Ok! thanks. let me try

**Comment by gavruk** [comment]
Did this worked?

**Comment by kyawmyintthein** [comment]
Sorry, I was busy with other things. It does not work.
![screen shot 2015-10-26 at 6 09 31 pm](https://cloud.githubusercontent.com/assets/3658706/10726288/bf71bb12-7c0c-11e5-9887-53799a1137d7.png)

**Comment by gavruk** [comment]
Can you show the list of js files included on your page?

**Comment by kyawmyintthein** [comment]
Ya! I got it. problem is fixed. I have to update angular-card to 0.3.4. Thanks

**Comment by gavruk** [comment]
If updating solved the issue, this means you've included `card.js` instead of `jquery.card.js`
