### ISSUE TITLE
Does not work with forms that the html atribute "name" contains DOT (.)

### ISSUE THREAD

**Issue by lucasmendonca** [gavruk/angular-card#13]
Does not work with forms that has name attr equals "form.cardForm", for example: 

``` javascript
<form name="form.cardForm">
```

Error output:
"Failed to execute 'querySelectorAll' on 'Document': '[name=form.cardForm]' is not a valid selector."(card.js:862:19)

I solved this problem changing the query selector:

``` javascript
'[name=' + attributes.name + ']'
```

to 

``` javascript
'[name="' + attributes.name + '"]' 
```

at card.js line 41

**Comment by gavruk** [comment]
Thanks.
This is fixed in v0.3.4
