### ISSUE TITLE
Support NPM package

### ISSUE THREAD

**Issue by anorsich** [gavruk/angular-card#14]

**Comment by bogusugob** [comment]
+1

**Comment by gavruk** [comment]
@anorsich @bogusugob npm package was already created by @duluca from his fork before this issue was created. So `angular-card` name is already taken.

**Comment by duluca** [comment]
@gavruk I've no issues ceding the name to you.

**Comment by gavruk** [comment]
@duluca will be great if you can combine your npm/browserify changes into a single commit and send pull request

**Comment by duluca** [comment]
@gavruk I will create the PR. What's your npm username? So I can add you as an owner of the package for publishing etc.

**Comment by gavruk** [comment]
@duluca the same as on github (gavruk)
Thank you :)

**Comment by duluca** [comment]
@gavruk sent the PR

**Comment by gavruk** [comment]
`npm install angular-card`
Thanks @duluca
