### ISSUE TITLE
Cannot load module

### ISSUE THREAD

**Issue by ghost** [gavruk/angular-card#18]
Hi,
I'm trying to load angular-card module but cannot make it work. Getting below error all the time;

```
 Uncaught Error: Cannot find module 'card'
Uncaught Error: [$injector:modulerr] Failed to instantiate module serviceboxApp due to:
Error: [$injector:modulerr] Failed to instantiate module gavruk.card due to:
Error: [$injector:nomod] Module 'gavruk.card' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

http://errors.angularjs.org/1.4.10/$injector/nomod?p0=gavruk.card
    at http://localhost:9000/bower_components/angular/angular.js:68:12
    at http://localhost:9000/bower_components/angular/angular.js:2012:17
    at ensure (http://localhost:9000/bower_components/angular/angular.js:1936:38)
    at module (http://localhost:9000/bower_components/angular/angular.js:2010:14)
    at http://localhost:9000/bower_components/angular/angular.js:4472:22
    at forEach (http://localhost:9000/bower_components/angular/angular.js:341:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4456:5)
    at http://localhost:9000/bower_components/angular/angular.js:4473:40
    at forEach (http://localhost:9000/bower_components/angular/angular.js:341:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4456:5)

```

---

Tried updating angular to version that card uses, as below and  doesn't work.

`8) angular#~1.4.8 which resolved to 1.4.10 and is required by angular-card#0.3.7`

Tried putting  'gavruk.card' to app.js and in the controller as below 

```

angular.module('serviceboxApp', [
   'gavruk.card',
  'serviceboxApp.auth',
  'serviceboxApp.admin',
  'serviceboxApp.constants',
```

```
and also tried;
 angular.module('serviceboxApp', ['gavruk.card'])

.controller('FinancesCtrl', ['$scope', '$state', 'Auth'  , function($scope, $state, Auth  ) {

```

this is my index.html and I see the js files included

```
      <script src="bower_components/card/lib/js/card.js"></script>
      <script src="bower_components/angular-card/src/card.js"></script>

```

and I'm using the same form template as in github repo readme but still getting the same error.
Do you have any idea what's I'm doing wrong? 
Thank you

**Comment by gavruk** [comment]
Hi @canercak
Does it work if you 
1. pull https://github.com/gavruk/angular-card
2. npm install
3. open example/example.html

**Comment by ghost** [comment]
it works. Trying to find whats wrong with my actual code..

**Comment by gavruk** [comment]
@canercak have you found an issue?

**Comment by burakkilic** [comment]
The same issue for me as well.

**Comment by gavruk** [comment]
@burakkilic can you create a simple example to reproduce this issue and send it to me?

**Comment by burakkilic** [comment]
@gavruk I guess I found the problem. If there are nested forms, it cannot find the module. It is working now after I put the form out of another one.

**Comment by ElielBarone** [comment]
In my case, the problem is that
var hasRequire = typeof require === 'function'; // true
so when he tries
 require('card') // Cannot find module 'card'(…)

**Comment by FelipeBarrosCruz** [comment]
That exacly @ElielBarone, for fix it:

`var hasRequire = window && window.angular ? false : typeof require === 'function';`

**Comment by geo242** [comment]
@gavruk Please merge this pull request

**Comment by gavruk** [comment]
Try v0.3.8
