### ISSUE TITLE
Bad link to css

### ISSUE THREAD

**Issue by ackuser** [gavruk/angular-card#2]
I think the link to the css is wrong, in fact, I cannot see if I clone the project or if I try to build it in another way

"GET /bower_components/card/lib/css/card.css" Error (404): "Not found"

**Comment by gavruk** [comment]
Looks like `card.css` does not exist when you run `bower install`.

**Comment by ackuser** [comment]
It is true, I notice that and I think it is not necessary.

**Comment by gavruk** [comment]
This is fixed in v0.2.0
