### ISSUE TITLE
container overflow

### ISSUE THREAD

**Issue by cdaringe** [gavruk/angular-card#20]
looks like something needs to be `clearfix`'d perhaps?

<img width="432" alt="screen shot 2016-04-16 at 2 11 29 pm" src="https://cloud.githubusercontent.com/assets/1003261/14583366/30a03324-03dd-11e6-9942-71d506123edd.png">

**Comment by cdaringe** [comment]
this occurs on mobile devices only, specifically, iPhone 4.  tried using default `<html>` as well as suggested in the examples

**Comment by cdaringe** [comment]
the child of the `card-container` doesn't honor/compute it's height correctly. e.g., the card-container may be `135px` computed height, yet the child `jp-container` computes a 200px. height

**Comment by gavruk** [comment]
@cdaringe This issue is probably related to original `card`, but not `angular-card` directives

**Comment by cdaringe** [comment]
Good point.  Thx
