### ISSUE TITLE
Remove requirement on form element

### ISSUE THREAD

**Issue by cybercyst** [gavruk/angular-card#7]
In a project I'm working on, I'm using a multi-part form, with nested ng-forms to validate each step. When trying to integrate angular-card, I get an error, since angular-card uses `document.querySelectorAll('form[name="cardForm"]');`  specifying a form element.  Could this be changed to `document.querySelectorAll('[name="cardForm"]');` or possibly `document.querySelectorAll('form[name="cardForm"],ng-form[name="cardForm"');`
I'm not sure if you'd have an even better suggestion, making this directive even more robust?

**Comment by gavruk** [comment]
This is fixed in v0.3.2
Thank you :)
