### ISSUE TITLE
It works before minification but not after

### ISSUE THREAD

**Issue by leer561** [gavruk/angular-card#9]
Javascript error Unknown provider: tProvider <- t after Rails minification Angularjs
 It works before minification but not after then it has to be an issue with something somewhere not using the min-safe injection method.
http://stackoverflow.com/questions/18950181/javascript-error-unknown-provider-tprovider-t-after-rails-minification-angul

**Comment by gavruk** [comment]
Thanks. This issue is fixed in v0.3.3
